import EditSpot from './EditSpot'
import Home from './Home'
import LoginFormModal from './LoginFormModal'
import MySpots from './MySpots'
import Navigation from './Navigation'
import NewSpot from './NewSpot'
import SignUpFormModal from './SignupFormModal'
import SingleSpot from './SingleSpot'
import UserReviews from './UserReviews'

